# This is a basic workflow to help you get started with Actions

name: Access to Secrets

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  display_access:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ secrets.USER_NAME }} 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Password
          echo ${{ secrets.PASSWORD }}
